language: eiffel
before_script:
    - export current_dir=$PWD ; echo current_dir=$current_dir ; cd ..
    - curl -sSL https://www.eiffel.org/setup/install.sh | bash > eiffel.rc
    - source ./eiffel.rc      
    - echo `ec -version`
    - cd $current_dir
    - git clone --depth 1 https://github.com/EiffelSoftware/libraries.git
    - export EIFFEL_SRC=$current_dir/libraries/Src
    - export ISE_LIBRARY=EIFFEL_SRC
    - echo Check projects compilation status...
branches:
  only:
  - master
  - develop
  - v1
  
script: compile_all -ecb -melt -list_failures -log_verbose -clean -options dotnet=false
group: stable
os: linux
