#!/bin/bash

web_dir=$1

mkdir $web_dir/html

# Install latest EiffelStudio suite.
curl -sSL https://www.eiffel.org/setup/install.sh > install_eiffel.sh \
        && bash ./install_eiffel.sh  latest > $HOME/eiffel.rc

# Setup Eiffel environment
source $HOME/eiffel.rc
export MYSQLINC=/usr/include/mysql
#export MYSQLLIB=/usr/lib/mysql
#export MYSQLLIB=/usr/lib/i386-linux-gnu
export MYSQLLIB=/usr/lib/x86_64-linux-gnu

cd $ISE_EIFFEL/library/store/dbms/rdbms/mysql/Clib && finish_freezing -library

cd $web_dir

# Get source code
git clone https://github.com/EiffelWebFramework/ROC.git $web_dir/src

# Build executable
eiffel build -v --target demo_libfcgi_with_mysql $web_dir/src/examples/demo/demo.ecf $web_dir/html/service.fcgi

# Clean files
rm -rf $ISE_EIFFEL
rm -rf $web_dir/src

exit $?
